# Generated by Django 2.2.4 on 2019-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191126_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='guestemail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='guestname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='hostemail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='hostname',
            field=models.CharField(max_length=30),
        ),
    ]
