# Generated by Django 2.2.4 on 2019-11-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191127_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('hostemail', models.CharField(max_length=100)),
                ('hostno', models.CharField(max_length=100)),
                ('isCheckOut', models.BooleanField()),
                ('checkInTime', models.CharField(max_length=20)),
                ('checkOutTime', models.CharField(max_length=20)),
            ],
        ),
    ]
