# Generated by Django 2.2.4 on 2019-11-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_checkin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
